### PR TITLE
Add datadog metrics reporting

### PR DESCRIPTION
**Pull request by SomeHats**

### CODE REVIEW

**Comment by nikcorg** [comment]
Approved

**Comment by leemhenson** [comment]
Approved by 🐕 🐕 🐕 🐕 🐕 🐕 🐕 🐕 🐕 

[Approved with PullApprove](https://pullapprove.com/musicglue/mg-express/pull-request/20/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=musicglue/mg-express)

**Comment by leemhenson** [comment]
@nikcorg try your approval again

**Comment by nikcorg** [comment]
Approved

**Comment by nikcorg** [comment]
@leemhenson looks like I don't have the aww-thaw-ree-tah!

**Comment by SomeHats** [comment]
Approved by @nikcorg 

[Approved with PullApprove](https://pullapprove.com/musicglue/mg-express/pull-request/20/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=musicglue/mg-express)

**Pull request merged**
